{
  "comments": [
    {
      "key": {
        "uuid": "af11ec15_a56843f2",
        "filename": "tests/conftest.py",
        "patchSetId": 4
      },
      "lineNbr": 180,
      "author": {
        "id": 123
      },
      "writtenOn": "2018-09-26T18:38:02Z",
      "side": 1,
      "message": "nicely done",
      "revId": "0069bf5f7e22667ddc704d4271e3328d81f7cbeb",
      "serverId": "655300a2-7a56-4504-9153-881edd907bea",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "790db77e_323a4d8b",
        "filename": "tests/test_data.py",
        "patchSetId": 4
      },
      "lineNbr": 10,
      "author": {
        "id": 123
      },
      "writtenOn": "2018-09-26T18:38:02Z",
      "side": 1,
      "message": "yeah all this should have been done to begin with, i appologize\n\nI learned about pytest.fixtures later :/",
      "revId": "0069bf5f7e22667ddc704d4271e3328d81f7cbeb",
      "serverId": "655300a2-7a56-4504-9153-881edd907bea",
      "unresolved": false
    }
  ]
}